spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.19.88:3306/oauth?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    username: dhome
    password: dhome
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999

eureka:
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path:}
      management.context-path: ${server.servlet.context-path:}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://172.28.51.62:8001/eureka/,http://172.28.51.59:8001/eureka/
    register-with-eureka: true
    fetch-registry: false